spring:
  datasource:
    url: jdbc:mysql://mysql:3306/skyblog?characterEncoding=utf-8&useSSL=false
    username: root
    password: zhuyst
  redis:
    database: 2
    host: redis
    port: 6379
    password:
    timeout: 6000