spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skyblog?characterEncoding=utf-8&useSSL=false
    username: test
    password: zhuyst
  redis:
    database: 2
    host: localhost
    port: 6379
    password:
    timeout: 6000